// Consistency-audit runner. Executes every static check and writes a
// machine-generated report to docs/audit/CONSISTENCY-REPORT.md. Re-runnable;
// read-only against source (no DB, no running app). Exit code 0 always — this
// is a reporting tool, not a gate (curate real issues into docs/audit/FINDINGS.md).
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { REPO } from './lib.mjs';
import { rbacTriangle } from './rbac-triangle.mjs';
import { enumParity } from './enum-parity.mjs';
import { decimalParity } from './decimal-parity.mjs';
import { paginationGuard } from './pagination-guard.mjs';
import { auditCoverage } from './audit-coverage.mjs';

const checks = [rbacTriangle, enumParity, decimalParity, paginationGuard, auditCoverage];

const results = checks.map((c) => c());
const total = results.reduce((n, r) => n + r.count, 0);

const header = [
  '# Abrican ERP — Consistency Audit Report',
  '',
  `_Generated by \`npm run audit:consistency\` on ${new Date().toISOString()}._`,
  '',
  `**${total}** potential discrepancies across **${checks.length}** checks. ` +
    'Severities: CRITICAL > HIGH > MEDIUM > LOW > INFO. This file is auto-generated — ' +
    'triage real issues into `docs/audit/FINDINGS.md`.',
  '',
  '---',
  '',
].join('\n');

const body = results.map((r) => r.md).join('\n---\n\n');

const outDir = join(REPO, 'docs', 'audit');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'CONSISTENCY-REPORT.md'), header + body, 'utf8');

console.log(`Consistency audit complete: ${total} items across ${checks.length} checks.`);
for (const r of results) {
  const title = r.md.split('\n')[0].replace('## ', '');
  console.log(`  ${r.count === 0 ? '✅' : '•'} ${title}: ${r.count}`);
}
console.log('Report: docs/audit/CONSISTENCY-REPORT.md');
